Improve test script

diff --git a/test/ku b/test/ku
--- a/test/ku
+++ b/test/ku
@@ -13,11 +13,17 @@ if [ $# -eq 1 -a "$1" = "-b" ]; then
 elif [ $# -eq 1 -a "$1" = "-c" ]; then
 	sudo kextunload -c "$CLASS_NAME" -v 1
 else
-	echo "Unloading kext..."
-	sudo kextunload "$KEXT" >/dev/null 2>&1 \
-		&& (echo "Kext unloaded"; exit 0)
+	if sudo kextunload "$KEXT" >/dev/null 2>&1; then
+		echo "Kext unloaded"
+		exit 0
+	fi
 	echo "Unloading class first..."
 	sudo kextunload -c "$CLASS_NAME" >/dev/null 2>&1
-	sudo kextunload "$KEXT" >/dev/null 2>&1 \
-		|| (echo "Failed."; exit 2)
+	if sudo kextunload "$KEXT" >/dev/null 2>&1; then
+		echo "Kext unloaded"
+		exit 0
+	else
+		echo "Failed"
+		exit 2
+	fi
 fi
